# ==============================================================================
# SCRIPT: Merge DEG Results and Identify MD-DEGs
# DATE: September 2, 2025
#
# DESCRIPTION:
# This script serves as the second part of the analysis pipeline. It takes the
# tissue-specific DEG result files generated by the first script, merges them
# into a single comprehensive dataset, and then identifies "Antibiotic and
# Sterile Condition-responsive DEGs" (MD-DEGs) based on specific
# regulation patterns across experimental conditions.
#
# PREREQUISITES:
#   - This script should be run after '02_DEG_Analysis.R'.
#   - The 'RESULTS_DIR' path must point to the same directory where the
#     'DEG_results_*.csv' files were saved.
#
# ==============================================================================


#
# Section 0: Setup and Environment
# ------------------------------------------------------------------------------

# --- 0.1: Load Required Libraries
library(dplyr)
library(purrr)
library(tidyr)

# --- 0.2: Define Paths
# IMPORTANT: This directory must contain the 'DEG_results_*.csv' files
# generated by the previous script.
RESULTS_DIR <- "/home/GM_SPF/DEG"

# Set the working directory
setwd(RESULTS_DIR)


#
# Section 1: Merge DEG Results and Identify MD-DEGs
# ------------------------------------------------------------------------------
cat("\n--- Merging DEG files and identifying MD-DEGs ---\n")

# --- 1.1: Find and merge all tissue-specific DEG result files
# Searches for all files starting with 'DEG_results_' and ending with '.csv'
deg_files <- list.files(path = RESULTS_DIR, pattern = "^DEG_results_.*\\.csv$", full.names = TRUE)

if (length(deg_files) > 0) {
  # Read all individual CSV files and combine them into one data frame
  merged_deg_data <- map_dfr(deg_files, read.csv)
  
  # Save the combined DEG file for reference and future use
  write.csv(merged_deg_data, file.path(RESULTS_DIR, "merged_DEG_all_tissues.csv"), row.names = FALSE)
  
  message(sprintf("Successfully merged %d DEG files into 'merged_DEG_all_tissues.csv'.", length(deg_files)))
  
  # --- 1.2: Identify MD-DEGs from the merged data
  # Definition of MD-DEGs:
  # - Positive: DOWN in (GF vs SPF) AND DOWN in (nABX vs SPF) AND UP in (ExGF vs GF)
  # - Negative: UP in (GF vs SPF) AND UP in (nABX vs SPF) AND DOWN in (ExGF vs GF)
  
  # This efficient dplyr approach groups by gene and checks if it meets the criteria
  # across the three required comparisons within the same tissue and cell type.
  MD_DEG <- merged_deg_data %>%
    group_by(Tissue, Cell_type, Gene_symbol) %>%
    summarise(
      # Check for the presence of each required regulation pattern by creating a unique key
      is_gf_down   = "GFvsSPF_Down" %in% paste(Comparison, Change, sep="_"),
      is_nabx_down = "nABXvsSPF_Down" %in% paste(Comparison, Change, sep="_"),
      is_exgf_up   = "ExGFvsGF_Up" %in% paste(Comparison, Change, sep="_"),
      is_gf_up     = "GFvsSPF_Up" %in% paste(Comparison, Change, sep="_"),
      is_nabx_up   = "nABXvsSPF_Up" %in% paste(Comparison, Change, sep="_"),
      is_exgf_down = "ExGFvsGF_Down" %in% paste(Comparison, Change, sep="_"),
      .groups = 'drop'
    ) %>%
    # Assign 'Positive' or 'Negative' status based on the logical checks
    mutate(
      Change = case_when(
        is_gf_down & is_nabx_down & is_exgf_up   ~ "Positive",
        is_gf_up   & is_nabx_up   & is_exgf_down ~ "Negative",
        TRUE ~ NA_character_
      )
    ) %>%
    # Remove genes that do not meet either criteria
    filter(!is.na(Change)) %>%
    select(Tissue, Cell_type, Gene = Gene_symbol, Change)
  
  # --- 1.3: Generate and save summary tables
  if (nrow(MD_DEG) > 0) {
    # A) Table with counts of Positive/Negative MD-DEGs per tissue
    MD_count <- MD_DEG %>%
      group_by(Tissue, Change) %>%
      summarise(n_genes = n_distinct(Gene), .groups = 'drop') %>%
      pivot_wider(names_from = Change, values_from = n_genes, values_fill = 0)
    
    # B) Table listing each unique MD-DEG for each tissue
    MD_tissue <- MD_DEG %>%
      select(Tissue, Change, Gene) %>%
      distinct()
    
    # --- 1.4: Save the final MD-DEG result files
    write.csv(MD_DEG, file.path(RESULTS_DIR, "MD_DEG.csv"), row.names = FALSE)
    write.csv(MD_count, file.path(RESULTS_DIR, "MD_count.csv"), row.names = FALSE)
    write.csv(MD_tissue, file.path(RESULTS_DIR, "MD_tissue.csv"), row.names = FALSE)
    
    message(sprintf("SUCCESS: MD-DEG analysis complete. Found %d MD-DEGs.", nrow(MD_DEG)))
    
  } else {
    message("No genes met the criteria for MD-DEGs after analysis.")
  }
  
} else {
  warning("No 'DEG_results_*.csv' files found in the specified directory. Skipping MD-DEG analysis.")
}

cat("\n--- Full pipeline complete. ---\n")
